### ISSUE TITLE
Ads on multiple pages

### ISSUE THREAD

**Issue by LouWii** [Adrotator/AdrotatorV2#7]
Hi !

First, thank you for providing AdRotator. It's clearly a great tool to handle several ad networks without the needs of handling dozens of API and lines of code.

I saw that recommandation :
`We also recommend that if you intend to use the control on multiple pages that you embed the above control in a separate User Control for your app and use that User Control for the pages you wish to implement it in.`

And I'm quite lost here. Do you mind explain that a little bit more ?

Also, I tried to keep only one AdRotator object, created programatically for all my app and pages. But when I try to include it on a second page, it throws an error. So I guess that's because it's not the proper way to do this.

Thanks for any help.

**Comment by SimonDarksideJ** [comment]
It refers to doing it through XAML and having a separate UserControl (there's an item template for it) and putting AdRotator in that.

Then whichever pages you need AdRotator, just add the UserControl instead of AdRotator it'self and job done.

Doing it through code is possible but is tricky to get right because of the different ways both AdRotator, XAML and the AdProvider controls are loaded.  Check the examples in the repo, I think there is one for Programmatic use, if not let me know and I'll see about adding one.

**Comment by SimonDarksideJ** [comment]
@LouWii did that help, can we close this issue?

**Comment by LouWii** [comment]
Yes thank you ! :)
